export const FETCH_SEARCH_END = 'FETCH_SEARCH_END';
export const FETCH_CURRENT_SONG = 'FETCH_CURRENT_SONG';
export const HANDLE_PAUSE_OR_PLAY = 'HANDLE_PAUSE_OR_PLAY';
export const IS_CURRENT_SONG_PAUSED = 'IS_CURRENT_SONG_PAUSED';
export const IS_FETCHING = 'IS_FETCHING';